# Generated by Django 6.0 on 2025-12-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketTypr',
            new_name='TicketType',
        ),
    ]
