# Generated by Django 6.0 on 2025-12-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_tickettypr_tickettype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketType',
            new_name='TicketTier',
        ),
    ]
