# Generated by Django 6.0 on 2025-12-16 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_tickettype_tickettier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='backstage_limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='backstage_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='standard_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_limit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('ticket_type', models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('BACKSTAGE', 'Backstage')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'unique_together': {('event', 'customer')},
            },
        ),
        migrations.DeleteModel(
            name='TicketTier',
        ),
    ]
