# Generated by Django 6.0 on 2025-12-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_organizer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'customer', 'ticket_type')},
        ),
    ]
